#server
server:
  port: 18080

#application
application:
  environment : dev

#spring
spring:
  profiles:
      active: dev
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate :
        ddl_auto : create #create/validate
        format_sql : true
    show-sql: true
logging:
  level:
    root: DEBUG
    org.hibernate.type.descriptor.sql : trace
