#server
server:
  port: 18080

#application
application:
  environment : dev

#spring
spring:
  profiles:
      active: dev
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
logging:
  level:
    root: DEBUG
    org.springframework.jdbc.core: TRACE
