server:
  port: 18080
application:
  environment : dev
spring:
  profiles:
      active: dev
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
mybatis:
  mapper-locations: classpath*:/mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    call-setters-on-nulls: true

